version: "3"
services:
  dotenv:
    image: ghcr.io/tonsh/doenv:release
    container_name: dotenv
    restart: always
    env_file: .env
  redis:
    image: redis:latest
    container_name: dotenv-redis
    restart: always
    volumes:
      - "/data/redis_data:/data"
